REGTOOL       = {{ python }} {{ regtool }}
REGTOOL_OPT   =  --logical_name {{ libname }}

REGTOOL_FILES = $( find {{ dir_script }} -type f )

FILE_IN       = {{ file_in }} 
FILES_OUT     = {{ file_vhdl_pkg }}
FILES_OUT    += {{ file_vhdl_csr }}
FILES_OUT    += {{ file_md }}
FILES_OUT    += {{ file_h }}

{% if copy_dir %}
COPY_DIR      = {{ copy_dir }}
all      :  $(COPY_DIR)/$(notdir {{ file_vhdl_pkg }}) \
			$(COPY_DIR)/$(notdir {{ file_vhdl_csr }}) \
			$(COPY_DIR)/$(notdir {{ file_md }}) \
			$(COPY_DIR)/$(notdir {{ file_h }})

$(COPY_DIR) :
	mkdir -p "$@"

$(COPY_DIR)/$(notdir {{ file_vhdl_pkg }}) : {{ file_vhdl_pkg }} | $(COPY_DIR)
	cp $< $@

$(COPY_DIR)/$(notdir {{ file_vhdl_csr }}) : {{ file_vhdl_csr }} | $(COPY_DIR)
	cp $< $@

$(COPY_DIR)/$(notdir {{ file_md }}) : {{ file_md }} | $(COPY_DIR)
	cp $< $@

$(COPY_DIR)/$(notdir {{ file_h }}) : {{ file_h }} | $(COPY_DIR)
	cp $< $@

{% else %}
all      : $(FILES_OUT)

{% endif %}

{{ file_vhdl_pkg }} : \
  $(FILE_IN) $(REGTOOL_FILES)
	echo $(REGTOOL_FILES)
	$(REGTOOL) $(REGTOOL_OPT) $< --vhdl_package $@

{{ file_vhdl_csr }} : \
  $(FILE_IN) $(REGTOOL_FILES)
	$(REGTOOL) $(REGTOOL_OPT) $< --vhdl_module  $@

{{ file_md }} : \
  $(FILE_IN) $(REGTOOL_FILES)
	$(REGTOOL) $(REGTOOL_OPT) $< --doc_markdown $@

{{ file_h }} : \
  $(FILE_IN) $(REGTOOL_FILES)
	$(REGTOOL) $(REGTOOL_OPT) $< --c_header     $@

clean :
	rm -f $(FILES_OUT)
