{begin template}
-------------------------------------------------------------------
-- This file was generated by a script. Do not edit manually.
-------------------------------------------------------------------
-- Name        : {name}
-- Date        : {timestamp}
-- Description : Single Port ROM
-------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package {name}_pkg is

    constant {name}_ADDR_WIDTH : integer := {addr_width};  -- Address width (number of bits)
    constant {name}_DATA_WIDTH : integer := {data_width};  -- Data width (number of bits)

    component {name} is
        port (
            clk_i           : in  std_logic;
            cke_i           : in  std_logic;
            address_i       : in  std_logic_vector({name}_ADDR_WIDTH-1 downto 0);
            instruction_o   : out std_logic_vector({name}_DATA_WIDTH-1 downto 0)
        );
    end component {name};
    
end package {name}_pkg;

{end template}