VPATH        = /home/semai/Work/REPO_HOME/asylum/OpenBlaze8/tools/pbccv2-src-20110901/sdcc3/src/pblaze
srcdir       = /home/semai/Work/REPO_HOME/asylum/OpenBlaze8/tools/pbccv2-src-20110901/sdcc3/src/pblaze
top_builddir = ../..
top_srcdir   = /home/semai/Work/REPO_HOME/asylum/OpenBlaze8/tools/pbccv2-src-20110901/sdcc3

# Make all in this directory
include $(srcdir)/../port.mk

