{begin template}
-------------------------------------------------------------------
-- This file was generated by a script. Do not edit manually.
-------------------------------------------------------------------
-- Name        : {name}
-- Date        : {timestamp}
-- Description : Single Port ROM
-------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.STD_LOGIC_ARITH.ALL;
use IEEE.STD_LOGIC_UNSIGNED.ALL;

entity {name} is
  port (
    clk_i           : in  std_logic;
    cke_i           : in  std_logic;
    address_i       : in  std_logic_vector({addr_width}-1 downto 0);
    instruction_o   : out std_logic_vector({data_width}-1 downto 0)
    );
end {name};
--
architecture rtl of {name} is

begin

  process (clk_i) is
  begin  -- process
    if rising_edge(clk_i)
    then
      if (cke_i = '1')
      then
        case conv_integer(address_i) is
{CASE_BODY-10-instruction_o}
          when others => instruction_o <= (others => '0');
        end case;
      end if;
    end if;
  end process;
  
end rtl;
{end template}
